# Generated by Django 4.0.2 on 2024-01-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='token_app.token')),
            ],
        ),
        migrations.AddField(
            model_name='ico',
            name='smart_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='token_app.smartcontract'),
        ),
    ]
