# Generated by Django 4.0.2 on 2024-01-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0004_smartcontract_ico_smart_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
