# Generated by Django 4.0.2 on 2024-01-10 15:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_activity1_activity2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
