# Generated by Django 4.0.2 on 2024-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
