# Generated by Django 4.0.2 on 2024-01-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_adminreply_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreply',
            name='user_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.message'),
        ),
    ]
