# Generated by Django 4.0.2 on 2024-01-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_adminreply_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreply',
            name='sent_to_user',
            field=models.BooleanField(default=False),
        ),
    ]
