# Generated by Django 4.0.2 on 2024-01-13 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_homedescription_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity2',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
