# Generated by Django 4.0.2 on 2024-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_activity2_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
