# Generated by Django 4.0.2 on 2024-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_transaction_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedescription',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homedescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
