# Generated by Django 4.0.2 on 2024-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_homedescription_link_homedescription_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='about1',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about1',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
