# Generated by Django 4.0.2 on 2024-01-14 05:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_about2_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcontract',
            name='token',
        ),
        migrations.DeleteModel(
            name='TokenDescription',
        ),
        migrations.DeleteModel(
            name='TokenDescription1',
        ),
        migrations.DeleteModel(
            name='TokenDescription2',
        ),
        migrations.DeleteModel(
            name='TokenDescription3',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='smart_contract',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
        migrations.RemoveField(
            model_name='token',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='token',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='tokenpurchase',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='A',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='token',
            name='B',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='C',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='token',
            name='D',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='token',
            name='a',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='token',
            name='b',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='token',
            name='buy_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='description1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='join_us_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SmartContract',
        ),
    ]
