# Generated by Django 4.0.2 on 2024-01-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_tokendescription_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendescription',
            name='A',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
