# Generated by Django 4.0.2 on 2024-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICO',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='start_date',
        ),
        migrations.AddField(
            model_name='timer',
            name='day',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='timer',
            name='hours',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='timer',
            name='minutes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='timer',
            name='seconds',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendescription',
            name='days',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendescription',
            name='hours',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendescription',
            name='minutes',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tokendescription',
            name='seconds',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='a',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='b',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.DeleteModel(
            name='TokenPurchase',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
