# Generated by Django 4.0.2 on 2024-01-15 04:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_delete_ico_remove_userwallet_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('A', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('B', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('C', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('D', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('link_description', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
