# Generated by Django 4.0.2 on 2024-01-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity1',
            new_name='Roadmap1',
        ),
        migrations.RenameModel(
            old_name='Activity2',
            new_name='Roadmap2',
        ),
    ]
