# Generated by Django 4.0.2 on 2024-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_delete_activity3_remove_adminreply_user_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
