# Generated by Django 4.0.2 on 2024-01-15 13:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_delete_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', ckeditor.fields.RichTextField()),
                ('description2', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
