# Generated by Django 4.0.2 on 2024-01-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_footerdescription_footerlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about1',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
