# Generated by Django 4.0.2 on 2024-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_about1_image_file_alter_activity_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about1',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='usr/src/app/media/images/'),
        ),
    ]
