# Generated by Django 4.0.2 on 2024-01-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_activity_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlinks',
            old_name='link',
            new_name='profile_url',
        ),
        migrations.RemoveField(
            model_name='footerlinks',
            name='link_description',
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
