# Generated by Django 4.0.2 on 2024-01-23 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_rename_link_footerlinks_profile_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AddField(
            model_name='footerdescription',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footerdescription',
            name='description1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footerdescription',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
