# Generated by Django 4.0.2 on 2024-01-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendescription',
            name='days',
        ),
        migrations.RemoveField(
            model_name='tokendescription',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='tokendescription',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='tokendescription',
            name='seconds',
        ),
    ]
