# Generated by Django 4.0.2 on 2024-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_remove_tokendescription_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendescription',
            name='A',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='C',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='D',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='a',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='tokendescription',
            name='b',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
