# Generated by Django 4.0.2 on 2024-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_tokendescription_a_alter_tokendescription_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_only_count', models.IntegerField(default=0)),
            ],
        ),
    ]
